// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {chat} from '../models';

export function GetContacts():Promise<Array<chat.Contact>>;

export function SendMessage(arg1:string):Promise<void>;
