// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {chat} from '../models';

export function GetContacts():Promise<Array<chat.Contact>>;

export function GetMessages(arg1:string,arg2:number):Promise<Array<chat.PlainMessage>>;

export function SendMessage(arg1:string,arg2:string):Promise<void>;
