// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetContacts() {
  return window['go']['main']['App']['GetContacts']();
}

export function GetMessages(arg1, arg2) {
  return window['go']['main']['App']['GetMessages'](arg1, arg2);
}

export function SendMessage(arg1, arg2) {
  return window['go']['main']['App']['SendMessage'](arg1, arg2);
}
